// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spydomo.Models;

#nullable disable

namespace Spydomo.Models.Migrations
{
    [DbContext(typeof(SpydomoContext))]
    [Migration("20260212202627_UpdateSignalTypes")]
    partial class UpdateSignalTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spydomo.Models.AggregatedCounter", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Key")
                        .HasName("PK_HangFire_CounterAggregated");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_AggregatedCounter_ExpireAt")
                        .HasFilter("([ExpireAt] IS NOT NULL)");

                    b.ToTable("AggregatedCounter", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.AiUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<double>("CostUsd")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AiUsageLogs");
                });

            modelBuilder.Entity("Spydomo.Models.CanonicalTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CanonicalTags");
                });

            modelBuilder.Entity("Spydomo.Models.CanonicalTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CanonicalThemes");
                });

            modelBuilder.Entity("Spydomo.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CleanupCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletionRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlanCompaniesCount")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubscriptionCancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubscriptionNextBillingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrackedCompaniesCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("RegionCode");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Spydomo.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CategoryConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<string>("CategoryEvidenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryReason")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("HasFacebookReviews")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastCompanyDataUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastFacebookLookup")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastFacebookReviewsLookup")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLinkedinLookup")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRedditLookup")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PrimaryCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SelfDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfPositioning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NEW");

                    b.Property<string>("Url")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("URL");

                    b.HasKey("Id")
                        .HasName("PK_Organizations");

                    b.HasIndex("PrimaryCategoryId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CompanyCategories", (string)null);
                });

            modelBuilder.Entity("Spydomo.Models.CompanyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("CompanyGroups");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyGroupStrategicSummaryState", b =>
                {
                    b.Property<int>("CompanyGroupId")
                        .HasColumnType("int");

                    b.Property<int>("LastProcessedSummarizedInfoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastRunUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CompanyGroupId");

                    b.ToTable("CompanyGroupStrategicSummaryStates");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyKeywords");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgEngagementScore")
                        .HasColumnType("float");

                    b.Property<int?>("CompanyGroupId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyPostCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NegativeCount")
                        .HasColumnType("int");

                    b.Property<int>("NeutralCount")
                        .HasColumnType("int");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PositiveCount")
                        .HasColumnType("int");

                    b.Property<double>("PrevAvgEngagementScore")
                        .HasColumnType("float");

                    b.Property<int>("PrevCompanyPostCount")
                        .HasColumnType("int");

                    b.Property<int>("PrevNegativeCount")
                        .HasColumnType("int");

                    b.Property<int>("PrevPositiveCount")
                        .HasColumnType("int");

                    b.Property<int>("PrevUserMentionCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceBreakdownJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopTagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopThemesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserMentionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyGroupId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyStats");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyTargetSegment", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("TargetSegmentId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId", "TargetSegmentId");

                    b.HasIndex("TargetSegmentId");

                    b.ToTable("CompanyTargetSegments");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyUserPersona", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UserPersonaId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId", "UserPersonaId");

                    b.HasIndex("UserPersonaId");

                    b.ToTable("CompanyUserPersonas");
                });

            modelBuilder.Entity("Spydomo.Models.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("Spydomo.Models.CompetitorName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitorId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId");

                    b.ToTable("CompetitorNames");
                });

            modelBuilder.Entity("Spydomo.Models.Counter", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Key", "Id")
                        .HasName("PK_HangFire_Counter");

                    b.ToTable("Counter", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Spydomo.Models.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TypeId");

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("Spydomo.Models.DataSourceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlKeywords")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DataSourceTypes");
                });

            modelBuilder.Entity("Spydomo.Models.FilteredUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceTypeId");

                    b.HasIndex("CompanyId", "PostUrl", "SourceTypeId")
                        .IsUnique();

                    b.ToTable("FilteredUrls");
                });

            modelBuilder.Entity("Spydomo.Models.GroupSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("GroupSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("Pulse");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TimeWindowDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.HasKey("Id")
                        .HasName("PK_GroupSnapshots");

                    b.HasIndex("GroupSlug")
                        .HasDatabaseName("IX_GroupSnapshots_GroupSlug");

                    b.HasIndex("GroupId", "Kind", "TimeWindowDays", "GeneratedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_GroupSnapshots_GroupId_Kind_Window_Generated");

                    b.ToTable("GroupSnapshots", (string)null);
                });

            modelBuilder.Entity("Spydomo.Models.Hash", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key", "Field")
                        .HasName("PK_HangFire_Hash");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_Hash_ExpireAt")
                        .HasFilter("([ExpireAt] IS NOT NULL)");

                    b.ToTable("Hash", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime");

                    b.Property<string>("InvocationData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_HangFire_Job");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_Job_ExpireAt")
                        .HasFilter("([ExpireAt] IS NOT NULL)");

                    b.HasIndex(new[] { "StateName" }, "IX_HangFire_Job_StateName")
                        .HasFilter("([StateName] IS NOT NULL)");

                    b.ToTable("Job", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.JobParameter", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId", "Name")
                        .HasName("PK_HangFire_JobParameter");

                    b.ToTable("JobParameter", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.JobQueue", b =>
                {
                    b.Property<string>("Queue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.HasKey("Queue", "Id")
                        .HasName("PK_HangFire_JobQueue");

                    b.ToTable("JobQueue", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.LaunchNotification", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasColumnName("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Email", "Date");

                    b.ToTable("LaunchNotifications");
                });

            modelBuilder.Entity("Spydomo.Models.List", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key", "Id")
                        .HasName("PK_HangFire_List");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_List_ExpireAt")
                        .HasFilter("([ExpireAt] IS NOT NULL)");

                    b.ToTable("List", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.PulseObservationIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateBucket")
                        .HasColumnType("date");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DateBucket");

                    b.HasIndex("CompanyId", "Type", "TopicKey", "DateBucket")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Type", "TopicKey", "FirstSeenAt");

                    b.ToTable("PulseObservationIndices");
                });

            modelBuilder.Entity("Spydomo.Models.PulseTopicState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Type", "TopicKey")
                        .IsUnique();

                    b.ToTable("PulseTopicStates");
                });

            modelBuilder.Entity("Spydomo.Models.RawContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<float?>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataSourceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("EngagementScore")
                        .HasColumnType("int");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessingAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DataSourceTypeId");

                    b.ToTable("RawContents");
                });

            modelBuilder.Entity("Spydomo.Models.Region", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.HasIndex("CountryCode");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Spydomo.Models.Schema", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Version")
                        .HasName("PK_HangFire_Schema");

                    b.ToTable("Schema", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.SemanticSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Classifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IntentsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeywordsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<double?>("ModelScore")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<int?>("RawContentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("SummarizedInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("CompanyId", "SeenAt");

                    b.ToTable("SemanticSignals");
                });

            modelBuilder.Entity("Spydomo.Models.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_HangFire_Server");

                    b.HasIndex(new[] { "LastHeartbeat" }, "IX_HangFire_Server_LastHeartbeat");

                    b.ToTable("Server", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.Set", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Key", "Value")
                        .HasName("PK_HangFire_Set");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_HangFire_Set_ExpireAt")
                        .HasFilter("([ExpireAt] IS NOT NULL)");

                    b.HasIndex(new[] { "Key", "Score" }, "IX_HangFire_Set_Score");

                    b.ToTable("Set", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.SignalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowedInLlm")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("SignalTypes");
                });

            modelBuilder.Entity("Spydomo.Models.SnapshotJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataSourceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DateFilter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DataSourceTypeId");

                    b.HasIndex("SnapshotId")
                        .IsUnique();

                    b.ToTable("SnapshotJobs");
                });

            modelBuilder.Entity("Spydomo.Models.State", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobId", "Id")
                        .HasName("PK_HangFire_State");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_HangFire_State_CreatedAt");

                    b.ToTable("State", "HangFire");
                });

            modelBuilder.Entity("Spydomo.Models.StrategicSignalCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StrategicSignalCache");
                });

            modelBuilder.Entity("Spydomo.Models.StrategicSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncludedSignalTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("RawContentId")
                        .HasColumnType("int");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SummarizedInfoId")
                        .HasColumnType("int");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tier")
                        .HasColumnType("int");

                    b.Property<string>("TierReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyGroupId", "PeriodType", "SourceKey")
                        .IsUnique()
                        .HasFilter("[SourceKey] IS NOT NULL AND [SourceKey] <> ''");

                    b.ToTable("StrategicSummaries");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Gist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GistGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GistPointsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GistSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("int");

                    b.Property<int?>("RawContentId")
                        .HasColumnType("int");

                    b.Property<int?>("Sentiment")
                        .HasColumnType("int");

                    b.Property<string>("SentimentReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalScore")
                        .HasColumnType("int");

                    b.Property<int?>("SourceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RawContentId");

                    b.HasIndex("SourceTypeId");

                    b.ToTable("SummarizedInfos");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoCompetitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompetitorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("SummarizedInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("SummarizedInfoId");

                    b.ToTable("SummarizedInfoCompetitors");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoSignalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SignalTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SummarizedInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SignalTypeId");

                    b.HasIndex("SummarizedInfoId");

                    b.ToTable("SummarizedInfoSignalTypes");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CanonicalTagId")
                        .HasColumnType("int");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SummarizedInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTagId");

                    b.HasIndex("SummarizedInfoId");

                    b.ToTable("SummarizedInfoTags");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CanonicalThemeId")
                        .HasColumnType("int");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SummarizedInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalThemeId");

                    b.HasIndex("SummarizedInfoId");

                    b.ToTable("SummarizedInfoThemes");
                });

            modelBuilder.Entity("Spydomo.Models.TargetSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TargetSegments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SMB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MidMarket"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Enterprise"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Agencies"
                        });
                });

            modelBuilder.Entity("Spydomo.Models.ThemeStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AverageSignalScore")
                        .HasColumnType("real");

                    b.Property<double>("AvgEngagementScore")
                        .HasColumnType("float");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompetitorMentionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MentionsCount")
                        .HasColumnType("int");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PrevMentionsCount")
                        .HasColumnType("int");

                    b.Property<int>("SentimentNegativeCount")
                        .HasColumnType("int");

                    b.Property<int>("SentimentPositiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.Property<string>("TopTagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalEngagementScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalSignalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ThemeId");

                    b.HasIndex("ClientId", "CompanyId", "ThemeId", "PeriodType", "StartDate", "EndDate")
                        .IsUnique();

                    b.ToTable("ThemeStats");
                });

            modelBuilder.Entity("Spydomo.Models.TrackedCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_FeedbackLoops");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("TrackedCompanies");
                });

            modelBuilder.Entity("Spydomo.Models.TrackedCompanyGroup", b =>
                {
                    b.Property<int>("TrackedCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyGroupId")
                        .HasColumnType("int");

                    b.HasKey("TrackedCompanyId", "CompanyGroupId");

                    b.HasIndex("CompanyGroupId");

                    b.ToTable("TrackedCompanyGroups");
                });

            modelBuilder.Entity("Spydomo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("InvitationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Spydomo.Models.UserPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserPersonas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Support"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 5,
                            Name = "DataAnalytics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("Spydomo.Models.Client", b =>
                {
                    b.HasOne("Spydomo.Models.Country", "CountryCodeNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("FK_Clients_Countries");

                    b.HasOne("Spydomo.Models.Region", "RegionCodeNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("RegionCode")
                        .HasConstraintName("FK_Clients_Regions");

                    b.Navigation("CountryCodeNavigation");

                    b.Navigation("RegionCodeNavigation");
                });

            modelBuilder.Entity("Spydomo.Models.Company", b =>
                {
                    b.HasOne("Spydomo.Models.CompanyCategory", "PrimaryCategory")
                        .WithMany("Companies")
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryCategory");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyGroup", b =>
                {
                    b.HasOne("Spydomo.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyGroupStrategicSummaryState", b =>
                {
                    b.HasOne("Spydomo.Models.CompanyGroup", "CompanyGroup")
                        .WithOne()
                        .HasForeignKey("Spydomo.Models.CompanyGroupStrategicSummaryState", "CompanyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyGroup");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyKeyword", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyStats", b =>
                {
                    b.HasOne("Spydomo.Models.CompanyGroup", "CompanyGroup")
                        .WithMany()
                        .HasForeignKey("CompanyGroupId");

                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompanyGroup");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyTargetSegment", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany("CompanyTargetSegments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.TargetSegment", "TargetSegment")
                        .WithMany("CompanyTargetSegments")
                        .HasForeignKey("TargetSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("TargetSegment");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyUserPersona", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany("CompanyUserPersonas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.UserPersona", "UserPersona")
                        .WithMany("CompanyUserPersonas")
                        .HasForeignKey("UserPersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("UserPersona");
                });

            modelBuilder.Entity("Spydomo.Models.CompetitorName", b =>
                {
                    b.HasOne("Spydomo.Models.Competitor", "Competitor")
                        .WithMany()
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompetitorNames_Competitors");

                    b.Navigation("Competitor");
                });

            modelBuilder.Entity("Spydomo.Models.DataSource", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany("DataSources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_DataSources_Organizations");

                    b.HasOne("Spydomo.Models.DataSourceType", "Type")
                        .WithMany("DataSources")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_DataSources_DataSourceTypes");

                    b.Navigation("Company");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Spydomo.Models.FilteredUrl", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.DataSourceType", "SourceType")
                        .WithMany()
                        .HasForeignKey("SourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("Spydomo.Models.GroupSnapshot", b =>
                {
                    b.HasOne("Spydomo.Models.CompanyGroup", "Group")
                        .WithMany("Snapshots")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GroupSnapshots_CompanyGroups");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Spydomo.Models.JobParameter", b =>
                {
                    b.HasOne("Spydomo.Models.Job", "Job")
                        .WithMany("JobParameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HangFire_JobParameter_Job");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Spydomo.Models.PulseObservationIndex", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Spydomo.Models.PulseTopicState", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Spydomo.Models.RawContent", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany("UserFeedbacks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserFeedbacks_Companies");

                    b.HasOne("Spydomo.Models.DataSourceType", "DataSourceType")
                        .WithMany("UserFeedbacks")
                        .HasForeignKey("DataSourceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFeedbacks_DataSourceTypes");

                    b.Navigation("Company");

                    b.Navigation("DataSourceType");
                });

            modelBuilder.Entity("Spydomo.Models.Region", b =>
                {
                    b.HasOne("Spydomo.Models.Country", "CountryCodeNavigation")
                        .WithMany("Regions")
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("FK_Regions_Countries");

                    b.Navigation("CountryCodeNavigation");
                });

            modelBuilder.Entity("Spydomo.Models.SemanticSignal", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Spydomo.Models.SnapshotJob", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.DataSourceType", "DataSourceType")
                        .WithMany()
                        .HasForeignKey("DataSourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DataSourceType");
                });

            modelBuilder.Entity("Spydomo.Models.State", b =>
                {
                    b.HasOne("Spydomo.Models.Job", "Job")
                        .WithMany("States")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HangFire_State_Job");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Spydomo.Models.StrategicSummary", b =>
                {
                    b.HasOne("Spydomo.Models.CompanyGroup", "CompanyGroup")
                        .WithMany()
                        .HasForeignKey("CompanyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");

                    b.Navigation("CompanyGroup");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfo", b =>
                {
                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany("SummarizedInfos")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Insights_Companies");

                    b.HasOne("Spydomo.Models.RawContent", "RawContent")
                        .WithMany()
                        .HasForeignKey("RawContentId");

                    b.HasOne("Spydomo.Models.DataSourceType", "SourceType")
                        .WithMany("SummarizedInfos")
                        .HasForeignKey("SourceTypeId")
                        .HasConstraintName("FK_Insights_DataSourceTypes");

                    b.Navigation("Company");

                    b.Navigation("RawContent");

                    b.Navigation("SourceType");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoCompetitor", b =>
                {
                    b.HasOne("Spydomo.Models.Competitor", "Competitor")
                        .WithMany("SummarizedInfoCompetitors")
                        .HasForeignKey("CompetitorId")
                        .HasConstraintName("FK_SummarizedInfoCompetitors_Competitors1");

                    b.HasOne("Spydomo.Models.SummarizedInfo", "SummarizedInfo")
                        .WithMany("SummarizedInfoCompetitors")
                        .HasForeignKey("SummarizedInfoId")
                        .HasConstraintName("FK_SummarizedInfoCompetitors_Insights");

                    b.Navigation("Competitor");

                    b.Navigation("SummarizedInfo");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoSignalType", b =>
                {
                    b.HasOne("Spydomo.Models.SignalType", "SignalType")
                        .WithMany()
                        .HasForeignKey("SignalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.SummarizedInfo", "SummarizedInfo")
                        .WithMany("SummarizedInfoSignalTypes")
                        .HasForeignKey("SummarizedInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignalType");

                    b.Navigation("SummarizedInfo");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoTag", b =>
                {
                    b.HasOne("Spydomo.Models.CanonicalTag", "CanonicalTag")
                        .WithMany()
                        .HasForeignKey("CanonicalTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Spydomo.Models.SummarizedInfo", "SummarizedInfo")
                        .WithMany("SummarizedInfoTags")
                        .HasForeignKey("SummarizedInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalTag");

                    b.Navigation("SummarizedInfo");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfoTheme", b =>
                {
                    b.HasOne("Spydomo.Models.CanonicalTheme", "CanonicalTheme")
                        .WithMany()
                        .HasForeignKey("CanonicalThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Spydomo.Models.SummarizedInfo", "SummarizedInfo")
                        .WithMany("SummarizedInfoThemes")
                        .HasForeignKey("SummarizedInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalTheme");

                    b.Navigation("SummarizedInfo");
                });

            modelBuilder.Entity("Spydomo.Models.ThemeStats", b =>
                {
                    b.HasOne("Spydomo.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.CanonicalTheme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Spydomo.Models.TrackedCompany", b =>
                {
                    b.HasOne("Spydomo.Models.Client", "Client")
                        .WithMany("TrackedCompanies")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedbackLoops_Clients");

                    b.HasOne("Spydomo.Models.Company", "Company")
                        .WithMany("TrackedCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeedbackLoops_Organizations");

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Spydomo.Models.TrackedCompanyGroup", b =>
                {
                    b.HasOne("Spydomo.Models.CompanyGroup", "CompanyGroup")
                        .WithMany("TrackedCompanyGroups")
                        .HasForeignKey("CompanyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spydomo.Models.TrackedCompany", "TrackedCompany")
                        .WithMany("TrackedCompanyGroups")
                        .HasForeignKey("TrackedCompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompanyGroup");

                    b.Navigation("TrackedCompany");
                });

            modelBuilder.Entity("Spydomo.Models.User", b =>
                {
                    b.HasOne("Spydomo.Models.Client", "Client")
                        .WithMany("Users")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Users_Clients");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Spydomo.Models.Client", b =>
                {
                    b.Navigation("TrackedCompanies");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Spydomo.Models.Company", b =>
                {
                    b.Navigation("CompanyTargetSegments");

                    b.Navigation("CompanyUserPersonas");

                    b.Navigation("DataSources");

                    b.Navigation("SummarizedInfos");

                    b.Navigation("TrackedCompanies");

                    b.Navigation("UserFeedbacks");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyCategory", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Spydomo.Models.CompanyGroup", b =>
                {
                    b.Navigation("Snapshots");

                    b.Navigation("TrackedCompanyGroups");
                });

            modelBuilder.Entity("Spydomo.Models.Competitor", b =>
                {
                    b.Navigation("SummarizedInfoCompetitors");
                });

            modelBuilder.Entity("Spydomo.Models.Country", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Spydomo.Models.DataSourceType", b =>
                {
                    b.Navigation("DataSources");

                    b.Navigation("SummarizedInfos");

                    b.Navigation("UserFeedbacks");
                });

            modelBuilder.Entity("Spydomo.Models.Job", b =>
                {
                    b.Navigation("JobParameters");

                    b.Navigation("States");
                });

            modelBuilder.Entity("Spydomo.Models.Region", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Spydomo.Models.SummarizedInfo", b =>
                {
                    b.Navigation("SummarizedInfoCompetitors");

                    b.Navigation("SummarizedInfoSignalTypes");

                    b.Navigation("SummarizedInfoTags");

                    b.Navigation("SummarizedInfoThemes");
                });

            modelBuilder.Entity("Spydomo.Models.TargetSegment", b =>
                {
                    b.Navigation("CompanyTargetSegments");
                });

            modelBuilder.Entity("Spydomo.Models.TrackedCompany", b =>
                {
                    b.Navigation("TrackedCompanyGroups");
                });

            modelBuilder.Entity("Spydomo.Models.UserPersona", b =>
                {
                    b.Navigation("CompanyUserPersonas");
                });
#pragma warning restore 612, 618
        }
    }
}
